### ISSUE TITLE
Redundant precommit hooks?

### ISSUE THREAD

**Issue by nsorros** [MantisAI/hfie#4]
https://github.com/MantisAI/hfie/blob/c4709e5cc15f5512c46a2dae769d9c9cec9e6045/Makefile#L21

I think we only want the default hooks in this case, the others are more relevant when `DVC` is being used. So we may want to change this to `pre-commit install`. Let me know what you think @ivyleavedtoadflax

**Comment by ivyleavedtoadflax** [comment]
Ah yes, my bad. Let's lose these.
