### ISSUE TITLE
Is endpoint the only command?

### ISSUE THREAD

**Issue by nsorros** [MantisAI/hfie#5]
`hfie --help` returns
```
Usage: hfie [OPTIONS] COMMAND [ARGS]...

Options:
  --install-completion [bash|zsh|fish|powershell|pwsh]
                                  Install completion for the specified shell.
  --show-completion [bash|zsh|fish|powershell|pwsh]
                                  Show completion for the specified shell, to
                                  copy it or customize the installation.
  --help                          Show this message and exit.

Commands:
  endpoint
```

Is there scope for additional additional commands? If not, do we want to simplify by removing the endpoint command and make it default

**Comment by nsorros** [comment]
From what I am seeing here there is also a provider endpoint https://huggingface.co/docs/inference-endpoints/api_reference so I assume we want to expand to this later, right? If so, I can create an issue for that and close this.

**Comment by ivyleavedtoadflax** [comment]
Yes, i planned to include provider too

**Comment by nsorros** [comment]
cool, closing in favor of #20
